name: Crear release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Resolver dependencias con Composer
      run: composer install --no-dev --optimize-autoloader
      
    - name: Empaquetar contenido del repositorio
      run: zip -r plugin.zip ./ -x "*.git*" "composer.*" ".gitignore"

    - name: Crear tag de commit
      if: github.ref == 'refs/heads/main'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a v${{ github.run_number }} -m "Versión ${{ github.run_number }}"

    - name: Obtener URL de carga de la release
      id: upload
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Subir contenido empaquetado como release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.upload.outputs.upload_url }}
        asset_path: ./plugin.zip
        asset_name: wp-order-tracker-plugin-.zip
        asset_content_type: application/zip
        release_id: ${{ github.event.release.id }}
